/**
 * Rebuild lib/ from src/: the browser half (src/client.js) is bundled with
 * esbuild into the __ModuleLoader__.load factory form dsh's web GUI expects,
 * and the host half (src/host.js) + typings are copied across. lib/ is
 * generated output and is not committed.
 */
import { buildSync } from "esbuild";
import { writeFileSync, mkdirSync, copyFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here);

const result = buildSync({
  entryPoints: [path.join(root, "src", "client.js")],
  bundle: true,
  format: "cjs",
  platform: "browser",
  target: ["es2022"],
  write: false,
  treeShaking: false,
  external: ["react", "react-dom", "react-dom/*", "react/jsx-runtime", "@deepseek-ai/*"],
  sourcemap: false,
  logLevel: "warning",
});

const body = result.outputFiles[0].text;
// The ModuleLoader invokes the factory with only `require` in scope; the
// bundled CJS body references bare `module`/`exports`, so they are declared
// here (the same preamble esbuild emits for first-party client bundles).
const PREAMBLE = "var module = { exports: {} };\n\t\tvar exports = module.exports;\n\t\t";
const wrapped = [
  "/** Generated by build.mjs — do not edit. */",
  "window.__ModuleLoader__.load({",
  '\tid: "dsh-model-select-plus",',
  "\tfactory: (require) => {",
  PREAMBLE + body.replace(/^/gm, "\t\t") + "\n\t\treturn module.exports;",
  "\t}",
  "});",
  "",
].join("\n");

mkdirSync(path.join(root, "lib"), { recursive: true });
writeFileSync(path.join(root, "lib", "client.cjs"), wrapped);
for (const f of ["host.js", "host.d.ts", "client.d.ts"]) {
  copyFileSync(path.join(root, "src", f), path.join(root, "lib", f));
}
console.log(`lib/ rebuilt: client.cjs (${wrapped.length} bytes), host.js, host.d.ts, client.d.ts`);
