/** Generated by scripts/build-client.mjs — do not edit. */
window.__ModuleLoader__.load({
	id: "dsh-plugin-dashboard",
	factory: (require) => {
var module = { exports: {} };
		var exports = module.exports;
				"use strict";
		var __create = Object.create;
		var __defProp = Object.defineProperty;
		var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
		var __getOwnPropNames = Object.getOwnPropertyNames;
		var __getProtoOf = Object.getPrototypeOf;
		var __hasOwnProp = Object.prototype.hasOwnProperty;
		var __export = (target, all) => {
		  for (var name in all)
		    __defProp(target, name, { get: all[name], enumerable: true });
		};
		var __copyProps = (to, from, except, desc) => {
		  if (from && typeof from === "object" || typeof from === "function") {
		    for (let key of __getOwnPropNames(from))
		      if (!__hasOwnProp.call(to, key) && key !== except)
		        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
		  }
		  return to;
		};
		var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
		  // If the importer is in node compatibility mode or this is not an ESM
		  // file that has been converted to a CommonJS file using a Babel-
		  // compatible transform (i.e. "__esModule" has not been set), then set
		  // "default" to the CommonJS "module.exports" for node compatibility.
		  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
		  mod
		));
		var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
		
		// src/client/main.ts
		var main_exports = {};
		__export(main_exports, {
		  apply: () => apply,
		  inject: () => inject
		});
		module.exports = __toCommonJS(main_exports);
		var import_react = __toESM(require("react"), 1);
		var ROUTE_PREFIX = "/plugins/dsh-plugin-dashboard/api";
		var S = {
		  card: { background: "#161b22", border: "1px solid #30363d", borderRadius: 10, padding: "12px 14px", marginBottom: 10, display: "flex", flexDirection: "column", gap: 8 },
		  row: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
		  name: { fontWeight: 600, wordBreak: "break-all" },
		  badge: { fontSize: 11, padding: "1px 8px", borderRadius: 999, border: "1px solid #30363d", color: "#8b949e" },
		  badgeGit: { color: "#c9a1ff", borderColor: "#4b3670" },
		  badgeNpm: { color: "#7ee787", borderColor: "#2d6a33" },
		  badgeUp: { color: "#d29922", borderColor: "#6b5318" },
		  desc: { color: "#8b949e", fontSize: 12, minHeight: "1em" },
		  vers: { display: "flex", justifyContent: "space-between", color: "#8b949e", fontSize: 13 },
		  versB: { color: "#e6edf3", fontWeight: 500 },
		  pill: { fontSize: 12, padding: "2px 10px", borderRadius: 999, border: "1px solid #30363d", color: "#8b949e", marginLeft: "auto" },
		  pillOk: { color: "#3fb950", borderColor: "#2d6a33" },
		  pillAvail: { color: "#d29922", borderColor: "#6b5318", fontWeight: 600 },
		  actions: { display: "flex", gap: 8 },
		  btn: { border: "1px solid #30363d", borderRadius: 6, padding: "6px 10px", cursor: "pointer", background: "#21262d", color: "#e6edf3", fontSize: 13 },
		  btnPrimary: { background: "#2f81f7", color: "#fff", borderColor: "transparent" },
		  btnDanger: { background: "#21262d", color: "#f85149", borderColor: "#6e2c2c" },
		  btnDisabled: { opacity: 0.45, cursor: "not-allowed" },
		  modalWrap: { position: "fixed", inset: 0, background: "rgba(1,4,9,.7)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 10 },
		  modal: { background: "#161b22", border: "1px solid #30363d", borderRadius: 12, maxWidth: 620, width: "100%", maxHeight: "80vh", display: "flex", flexDirection: "column" },
		  modalHead: { fontSize: 16, padding: "14px 16px", borderBottom: "1px solid #30363d" },
		  modalBody: { padding: "14px 16px", overflowY: "auto" },
		  plan: { display: "grid", gridTemplateColumns: "auto 1fr", gap: "6px 12px", fontSize: 13 },
		  planDt: { color: "#8b949e" },
		  planDd: { wordBreak: "break-all", fontFamily: "ui-monospace, monospace", fontSize: 12 },
		  log: { background: "#010409", border: "1px solid #30363d", borderRadius: 8, padding: 10, font: "12px/1.45 ui-monospace, monospace", maxHeight: 220, overflow: "auto", whiteSpace: "pre-wrap", marginTop: 10 },
		  modalFoot: { display: "flex", gap: 8, padding: "12px 16px", borderTop: "1px solid #30363d", justifyContent: "flex-end" },
		  banner: { background: "#3a2a08", border: "1px solid #d29922", color: "#e3c28f", padding: "8px 12px", borderRadius: 6, marginBottom: 12 },
		  empty: { color: "#8b949e", padding: 24, textAlign: "center" },
		  header: { display: "flex", alignItems: "center", gap: 10, marginBottom: 12 }
		};
		function short(s) {
		  return s ? s.slice(0, 7) : "";
		}
		function esc(s) {
		  return String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
		}
		var STATUS_PILL = {
		  "update-available": ["\u53EF\u5347\u7EA7", S.pillAvail],
		  "not-installed": ["\u672A\u5B89\u88C5", S.pillAvail],
		  "up-to-date": ["\u6700\u65B0", S.pillOk],
		  ahead: ["\u8D85\u524D", void 0],
		  unknown: ["\u672A\u77E5", void 0],
		  "n-a": ["n/a", void 0]
		};
		function Pill({ status }) {
		  const [label, style] = STATUS_PILL[status] ?? ["?", void 0];
		  return import_react.default.createElement("span", { style: { ...S.pill, ...style ?? {} } }, label);
		}
		function Card({ entry, onUpgrade, onUninstall }) {
		  const badges = [];
		  if (entry.isCore) badges.push(import_react.default.createElement("span", { key: "core", style: S.badge }, "core"));
		  if (entry.mounted) badges.push(import_react.default.createElement("span", { key: "mounted", style: S.badge }, "mounted"));
		  const sourceStyle = entry.source === "git" ? S.badgeGit : entry.source === "npm" ? S.badgeNpm : void 0;
		  badges.push(import_react.default.createElement("span", { key: "src", style: { ...S.badge, ...sourceStyle } }, entry.source));
		  if (entry.installedCommit) badges.push(import_react.default.createElement("span", { key: "commit", style: S.badge, title: entry.installedCommit }, short(entry.installedCommit)));
		  if (entry.upgradeable) badges.push(import_react.default.createElement("span", { key: "up", style: { ...S.badge, ...S.badgeUp } }, entry.status === "not-installed" ? "\u672A\u5B89\u88C5" : "\u6709\u65B0\u7248\u672C"));
		  let button;
		  if (entry.upgradeable) {
		    button = import_react.default.createElement("button", { style: { ...S.btn, ...S.btnPrimary }, onClick: () => onUpgrade(entry.name) }, "\u5347\u7EA7");
		  } else if (entry.status === "n-a" || entry.status === "unknown") {
		    button = import_react.default.createElement("button", { style: { ...S.btn, ...S.btnDisabled }, disabled: true, title: entry.latest?.error ?? "" }, "n/a");
		  } else {
		    button = import_react.default.createElement("button", { style: { ...S.btn, ...S.btnDisabled }, disabled: true }, "\u5DF2\u6700\u65B0");
		  }
		  const uninstallBtn = entry.isCore ? null : import_react.default.createElement("button", { style: { ...S.btn, ...S.btnDanger }, onClick: () => onUninstall(entry.name) }, "\u5378\u8F7D");
		  const latest = entry.latest?.label ?? "?";
		  return import_react.default.createElement(
		    "div",
		    { style: S.card },
		    import_react.default.createElement(
		      "div",
		      { style: S.row },
		      import_react.default.createElement("span", { style: S.name }, entry.name),
		      ...badges,
		      import_react.default.createElement(Pill, { status: entry.status })
		    ),
		    import_react.default.createElement("div", { style: S.desc }, esc(entry.description ?? "")),
		    import_react.default.createElement(
		      "div",
		      { style: S.vers },
		      import_react.default.createElement("span", null, "installed ", import_react.default.createElement("b", { style: S.versB }, esc(entry.installedVersion ?? "\u2014"))),
		      import_react.default.createElement("span", null, "latest ", import_react.default.createElement("b", { style: S.versB }, esc(latest)))
		    ),
		    import_react.default.createElement("div", { style: S.actions }, button, uninstallBtn)
		  );
		}
		var EMPTY_MODAL = { entry: void 0, plan: null, log: [], busy: false, done: false };
		function DashboardTab(props) {
		  const [entries, setEntries] = (0, import_react.useState)([]);
		  const [loading, setLoading] = (0, import_react.useState)(true);
		  const [error, setError] = (0, import_react.useState)(null);
		  const [dshRunning, setDshRunning] = (0, import_react.useState)(false);
		  const [modal, setModal] = (0, import_react.useState)(EMPTY_MODAL);
		  const [open, setOpen] = (0, import_react.useState)(false);
		  const [uninstallState, setUninstallState] = (0, import_react.useState)(null);
		  const reload = () => {
		    setLoading(true);
		    setError(null);
		    props.list().then((data) => {
		      setEntries(data.plugins);
		      setDshRunning(data.dshRunning);
		    }).catch((e) => setError(e.message)).finally(() => setLoading(false));
		  };
		  (0, import_react.useEffect)(() => {
		    reload();
		  }, []);
		  (0, import_react.useEffect)(() => {
		    if (!open && modal.done) {
		      setModal(EMPTY_MODAL);
		      reload();
		    }
		  }, [open, modal.done]);
		  const openUpgrade = (name) => {
		    const entry = entries.find((e) => e.name === name);
		    if (!entry) return;
		    setModal({ entry, plan: null, log: [], busy: true, done: false });
		    setOpen(true);
		    props.plan(name).then((plan) => setModal((m) => ({ ...m, plan, busy: false }))).catch((e) => {
		      setModal((m) => ({ ...m, plan: { name, source: "", installedVersion: null, installedCommit: null, currentSpecifier: "", targetLabel: "", targetCommit: null, newSpecifier: "", command: "", wouldChange: false, error: e.message }, busy: false }));
		    });
		  };
		  const doApply = () => {
		    if (!modal.plan) return;
		    setModal((m) => ({ ...m, busy: true }));
		    props.apply(modal.entry.name, modal.plan).then((out) => {
		      setModal((m) => ({ ...m, busy: false, done: out.applied, log: out.log }));
		    }).catch((e) => {
		      setModal((m) => ({ ...m, busy: false, log: [...m.log, `\u5931\u8D25\uFF1A${e.message}`] }));
		    });
		  };
		  const close = () => setOpen(false);
		  const openUninstall = (name) => {
		    const entry = entries.find((e) => e.name === name);
		    if (!entry) return;
		    setUninstallState({ entry, plan: null, log: [], busy: true, done: false });
		    props.uninstall(name, false).then((out) => {
		      setUninstallState((u) => u ? { ...u, plan: out.plan ?? null, busy: false } : u);
		    }).catch((e) => {
		      setUninstallState((u) => u ? { ...u, plan: { name, isCore: false, inDependencies: false, inBundles: false, wouldRemove: false, error: e.message }, busy: false } : u);
		    });
		  };
		  const doUninstall = () => {
		    if (!uninstallState?.entry) return;
		    setUninstallState((u) => u ? { ...u, busy: true } : u);
		    props.uninstall(uninstallState.entry.name, true).then((out) => {
		      setUninstallState((u) => u ? { ...u, busy: false, done: out.applied, log: out.log, plan: out.plan ?? u.plan } : u);
		    }).catch((e) => {
		      setUninstallState((u) => u ? { ...u, busy: false, log: [...u.log, `\u5931\u8D25\uFF1A${e.message}`] } : u);
		    });
		  };
		  const closeUninstall = () => {
		    setUninstallState(null);
		    reload();
		  };
		  return import_react.default.createElement(
		    "div",
		    null,
		    dshRunning ? import_react.default.createElement("div", { style: S.banner }, "\u26A0 dsh \u6B63\u5728\u8FD0\u884C\uFF1A\u5347\u7EA7\u4F1A\u6539\u52A8 profile \u7684 node_modules\uFF0C\u8BF7\u5148\u505C\u6B62 dsh \u518D\u5E94\u7528\u5347\u7EA7\u3002") : null,
		    import_react.default.createElement(
		      "div",
		      { style: S.header },
		      import_react.default.createElement("strong", null, `\u63D2\u4EF6\u7248\u672C\uFF08${entries.length}\uFF09`),
		      import_react.default.createElement("button", { style: S.btn, onClick: reload }, "\u5237\u65B0")
		    ),
		    loading ? import_react.default.createElement("div", { style: S.empty }, "\u67E5\u8BE2 npm registry + git \u8FDC\u7AEF\u2026") : error ? import_react.default.createElement("div", { style: S.empty }, `\u52A0\u8F7D\u5931\u8D25\uFF1A${esc(error)}`) : entries.length === 0 ? import_react.default.createElement("div", { style: S.empty }, "\u65E0\u63D2\u4EF6") : import_react.default.createElement("div", null, entries.map((e) => import_react.default.createElement(Card, { key: e.name, entry: e, onUpgrade: openUpgrade, onUninstall: openUninstall }))),
		    open ? import_react.default.createElement(UpgradeModal, { modal, onClose: close, onApply: doApply }) : null,
		    uninstallState ? import_react.default.createElement(UninstallModal, { state: uninstallState, onClose: closeUninstall, onApply: doUninstall }) : null
		  );
		}
		function UpgradeModal({ modal, onClose, onApply }) {
		  const plan = modal.plan;
		  const rows = [];
		  if (plan) {
		    rows.push(["\u6765\u6E90", plan.source], ["\u5F53\u524D", `${plan.installedVersion ?? "\u2014"}${plan.installedCommit ? ` (${short(plan.installedCommit)})` : ""}`], ["\u76EE\u6807", plan.targetLabel], ["\u65E7 specifier", plan.currentSpecifier], ["\u65B0 specifier", plan.newSpecifier]);
		    if (plan.error) rows.push(["\u9519\u8BEF", plan.error]);
		    else rows.push(["\u547D\u4EE4", import_react.default.createElement("code", null, esc(plan.command))]);
		  }
		  const canApply = plan != null && !plan.error && !modal.busy && !modal.done;
		  return import_react.default.createElement(
		    "div",
		    { style: S.modalWrap, onClick: onClose },
		    import_react.default.createElement(
		      "div",
		      { style: S.modal, onClick: (e) => e.stopPropagation() },
		      import_react.default.createElement("div", { style: S.modalHead }, `\u5347\u7EA7 ${modal.entry.name}`),
		      import_react.default.createElement(
		        "div",
		        { style: S.modalBody },
		        import_react.default.createElement(
		          "dl",
		          { style: S.plan },
		          ...rows.flatMap(([k, v]) => [
		            import_react.default.createElement("dt", { key: k + "-k", style: S.planDt }, k),
		            import_react.default.createElement("dd", { key: k + "-v", style: S.planDd }, v)
		          ])
		        ),
		        modal.log.length > 0 ? import_react.default.createElement("pre", { style: S.log }, modal.log.join("\n")) : null
		      ),
		      import_react.default.createElement(
		        "div",
		        { style: S.modalFoot },
		        import_react.default.createElement("button", { style: S.btn, onClick: onClose }, modal.done ? "\u5173\u95ED" : "\u53D6\u6D88"),
		        import_react.default.createElement(
		          "button",
		          { style: { ...S.btn, ...S.btnPrimary, ...canApply ? {} : S.btnDisabled }, disabled: !canApply, onClick: onApply, title: canApply ? "" : plan?.error ? plan.error : "\u5DF2\u662F\u6700\u65B0" },
		          modal.busy ? "\u6267\u884C pnpm install\u2026" : modal.done ? "\u5DF2\u5E94\u7528 \u2713 \u8BF7\u91CD\u542F dsh" : "\u5E94\u7528\u5347\u7EA7"
		        )
		      )
		    )
		  );
		}
		var inject = ["slots"];
		function apply(ctx) {
		  const api = `${ROUTE_PREFIX}`;
		  const list = async () => {
		    const res = await fetch(`${api}/list`);
		    const body = await res.json();
		    if (!res.ok) throw new Error(body.error ?? `list failed (${res.status})`);
		    return body;
		  };
		  const plan = async (name) => {
		    const res = await fetch(`${api}/upgrade`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name }) });
		    const body = await res.json();
		    if (!res.ok) throw new Error(body.error ?? `plan failed (${res.status})`);
		    return body.plan;
		  };
		  const apply2 = async (name, _plan) => {
		    const res = await fetch(`${api}/upgrade`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, apply: true }) });
		    const body = await res.json();
		    if (!res.ok) throw new Error(body.error ?? `upgrade failed (${res.status})`);
		    return body;
		  };
		  const uninstall = async (name, applyNow) => {
		    const res = await fetch(`${api}/uninstall`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, apply: applyNow }) });
		    const body = await res.json();
		    if (!res.ok) throw new Error(body.error ?? `uninstall failed (${res.status})`);
		    return body;
		  };
		  const injected = () => ({ list, plan, apply: apply2, uninstall });
		  if (!ctx.slots) return;
		  ctx.slots.inject(
		    "settings.plugins.tab",
		    () => ctx.slots.register({
		      name: "settings.plugins.tab",
		      id: "plugin-versions",
		      order: 20,
		      label: () => "\u63D2\u4EF6\u7248\u672C",
		      inject: injected
		    }, DashboardTab)
		  );
		}
		function UninstallModal({ state, onClose, onApply }) {
		  const plan = state.plan;
		  const rows = [];
		  if (plan) {
		    rows.push(["\u5F71\u54CD\u8303\u56F4", `${plan.inDependencies ? "dependencies + " : ""}${plan.inBundles ? "bundles \u6302\u8F7D" : ""}`]);
		    if (plan.error) rows.push(["\u9519\u8BEF", plan.error]);
		    else rows.push(["\u63D0\u793A", "pnpm remove \u540E\u4ECE bundles \u79FB\u9664\u6302\u8F7D\uFF1B\u5378\u8F7D\u540E\u9700\u8981\u91CD\u542F dsh \u751F\u6548"]);
		  }
		  const canApply = plan != null && !plan.error && !state.busy && !state.done;
		  return import_react.default.createElement(
		    "div",
		    { style: S.modalWrap, onClick: onClose },
		    import_react.default.createElement(
		      "div",
		      { style: { ...S.modal, borderColor: "#6e2c2c" }, onClick: (e) => e.stopPropagation() },
		      import_react.default.createElement("div", { style: S.modalHead }, `\u5378\u8F7D ${state.entry.name}`),
		      import_react.default.createElement(
		        "div",
		        { style: S.modalBody },
		        import_react.default.createElement(
		          "dl",
		          { style: S.plan },
		          ...rows.flatMap(([k, v]) => [
		            import_react.default.createElement("dt", { key: k + "-k", style: S.planDt }, k),
		            import_react.default.createElement("dd", { key: k + "-v", style: S.planDd }, v)
		          ])
		        ),
		        state.log.length > 0 ? import_react.default.createElement("pre", { style: S.log }, state.log.join("\n")) : null
		      ),
		      import_react.default.createElement(
		        "div",
		        { style: S.modalFoot },
		        import_react.default.createElement("button", { style: S.btn, onClick: onClose }, state.done ? "\u5173\u95ED" : "\u53D6\u6D88"),
		        import_react.default.createElement(
		          "button",
		          { style: { ...S.btn, ...S.btnDanger, ...canApply ? {} : S.btnDisabled }, disabled: !canApply, onClick: onApply, title: canApply ? "" : plan?.error ?? "" },
		          state.busy ? "\u6267\u884C pnpm remove\u2026" : state.done ? "\u5DF2\u5378\u8F7D \u2713 \u8BF7\u91CD\u542F dsh" : "\u786E\u8BA4\u5378\u8F7D"
		        )
		      )
		    )
		  );
		}
		
		return module.exports;
	}
});
