/**
 * Bundle the browser half (src/client/main.ts) into the ModuleLoader factory
 * form dsh's web GUI expects: window.__ModuleLoader__.load({ id, factory }).
 * The factory receives `require`, which resolves platform modules (react,
 * @deepseek-ai/*) from the shell; esbuild marks them external and emits a CJS
 * bundle whose module/exports/require bindings live inside the factory scope.
 */
import { buildSync } from "esbuild";
import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

const result = buildSync({
	entryPoints: [path.join(root, "src", "client", "main.ts")],
	bundle: true,
	format: "cjs",
	platform: "browser",
	target: ["es2022"],
	write: false,
	treeShaking: false,
	external: ["react", "react-dom", "react-dom/*", "react/jsx-runtime", "@deepseek-ai/*"],
	sourcemap: false,
	logLevel: "warning",
});

const body = result.outputFiles[0].text;
// The ModuleLoader invokes the factory with only `require` in scope; the
// bundled CJS body references bare `module`/`exports`, so they are declared
// here (the same preamble tsdown emits for first-party client bundles).
const PREAMBLE = "var module = { exports: {} };\n\t	var exports = module.exports;\n\t\t";
const wrapped = [
	"/** Generated by scripts/build-client.mjs — do not edit. */",
	"window.__ModuleLoader__.load({",
	'	id: "dsh-plugin-dashboard",',
	"	factory: (require) => {",
	PREAMBLE + body.replace(/^/gm, "\t\t") + "\n\t\treturn module.exports;",
	"	}",
	"});",
	"",
].join("\n");

mkdirSync(path.join(root, "lib"), { recursive: true });
writeFileSync(path.join(root, "lib", "client.cjs"), wrapped);
console.log(`lib/client.cjs (${wrapped.length} bytes)`);